#!/usr/bin/env python3
"""List available Copilot SDK models and write to documentation/available-models.md."""

import asyncio
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


async def main() -> None:
    try:
        from copilot import CopilotClient, SubprocessConfig
    except ImportError:
        print("ERROR: copilot SDK not installed. Run: pip install copilot-sdk", file=sys.stderr)
        sys.exit(1)

    cli_path = shutil.which("copilot")
    if not cli_path:
        print("ERROR: copilot binary not found on PATH.", file=sys.stderr)
        sys.exit(1)

    client = CopilotClient(SubprocessConfig(cli_path=cli_path, use_stdio=True))
    try:
        await client.start()
        models = await client.list_models()
    finally:
        await client.stop()

    if not models:
        print("No models returned from SDK.")
        sys.exit(1)

    # Sort by id
    models.sort(key=lambda m: m.id)

    # Print to stdout
    print(f"\n{'ID':<40} {'Name':<40} {'Reasoning Efforts'}")
    print("-" * 100)
    for m in models:
        efforts = ", ".join(m.supported_reasoning_efforts or []) or "—"
        print(f"{m.id:<40} {m.name:<40} {efforts}")

    # Write markdown doc
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    doc_path = PROJECT_ROOT / "documentation" / "available-models.md"
    doc_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Available Models",
        "",
        f"Last refreshed: {now}",
        "",
        "Generated by `scripts/list-models.py` via Copilot SDK `client.list_models()`.",
        "",
        "Set the model via the `SWARM_MODEL` environment variable.",
        "",
        "| Model ID | Name | Reasoning Efforts | Default Effort |",
        "| -------- | ---- | ----------------- | -------------- |",
    ]

    for m in models:
        efforts = ", ".join(m.supported_reasoning_efforts or []) or "—"
        default = m.default_reasoning_effort or "—"
        lines.append(f"| `{m.id}` | {m.name} | {efforts} | {default} |")

    lines.append("")
    doc_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWritten to {doc_path}")


if __name__ == "__main__":
    asyncio.run(main())
