"""initial schema

Revision ID: 21094e8dafe2
Revises:
Create Date: 2026-04-03 20:58:10.914669

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21094e8dafe2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('swarm_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_swarm', 'events', ['swarm_id', 'created_at'], unique=False)
    op.create_index('idx_events_type', 'events', ['swarm_id', 'event_type'], unique=False)
    op.create_table('swarms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('qa_refined_goal', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=30), server_default='starting', nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=True),
    sa.Column('synthesis_session_id', sa.String(length=200), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_round', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_rounds', sa.Integer(), server_default='8', nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('swarm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='idle', nullable=False),
    sa.Column('tasks_completed', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['swarm_id'], ['swarms.id'], ),
    sa.PrimaryKeyConstraint('swarm_id', 'name')
    )
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('swarm_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['swarm_id'], ['swarms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swarm_id', 'path', name='uq_files_swarm_path')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('swarm_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['swarm_id'], ['swarms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_swarm', 'messages', ['swarm_id', 'created_at'], unique=False)
    op.create_table('tasks',
    sa.Column('swarm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('worker_role', sa.String(length=100), nullable=False),
    sa.Column('worker_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('blocked_by', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('result', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['swarm_id'], ['swarms.id'], ),
    sa.PrimaryKeyConstraint('swarm_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_index('idx_messages_swarm', table_name='messages')
    op.drop_table('messages')
    op.drop_table('files')
    op.drop_table('agents')
    op.drop_table('swarms')
    op.drop_index('idx_events_type', table_name='events')
    op.drop_index('idx_events_swarm', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
